spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: fx-rate-consumer-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jc.kafka.common"
        spring.json.value.default.type: "com.jc.kafka.common.FxRate"

app:
  topic:
    fx-rates: fx-rates